name: test and deploy
on: [push]
jobs:
  execute-lint:
    runs-on: ubuntu-latest
    steps:
      - name: lint
        run: npm run lint
  execute-test:
    runs-on: ubuntu-latest
    steps:
      - name: test
        run: npm test
  execute-build:
    runs-on: ubuntu-latest
    steps:
      - name: build
        run: npm run build
