name: test and deploy
on: [push]
jobs:
  get-code:
    runs-on: ubuntu-latest
    steps: 
      - name: get code
        uses: actions/checkout@v4
      - name: npm install 
        run : npm ci

  execute-lint:
    needs: get-code
    runs-on: ubuntu-latest
    steps:
      - name: get code
        uses: actions/checkout@v4
      - name: npm install 
        run : npm ci
      - name: lint
        run: npm run lint
