name: test and deploy parallel
on: [push, workflow_dispatch]
jobs:
  execute-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v4
      - name: npm install 
        run : npm ci
      - name: lint
        run: npm run lint
  execute-test:
    needs: execute-lint
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v4
      - name: npm install 
        run : npm ci
      - name: test
        run: npm test
  execute-build:
    needs: execute-test
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v4
      - name: npm install 
        run : npm ci
      - name: build
        run: npm run build
