name: test and deploy parallel
on: [push, workflow_dispatch]
jobs:
  execute-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v4
      - name: npm install 
        run : npm ci
      - name: lint
        run: npm run lint
      - name: test
        run: npm test
      - name: build
        run: npm run build
